title: TSS
description: "Sounds of Tanacross"
theme: just-the-docs

url: http://gmholton.github.io/tss

#aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template


back_to_top: true

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e, %Y" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

search_enabled: false

# logo: /assets/images/caribou_banner.jpg

callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: yellow
  info:
    color: yellow
  tech:
    title: Technical Note
    color: yellow
    
gifpath: /assets/gif/
vidpath: http://www2.hawaii.edu/~holton/tss/assets/mp4/ # too large for github
audiopath: /assets/audio/

defaults:
  -
    scope:
      path: "letters" # 
      type: "pages"
    values:
      layout: "letter"
      nav_exclude: true
      speaker: "Mrs. Irene Arnold"
    
